### ISSUE TITLE
Strong ghosting...   🤔

### ISSUE THREAD

**Issue by Milincho** [mj-ehsan/NiceGuy-Shaders#13]
I see strong ghosting in Starfield when moving.

**Comment by mj-ehsan** [comment]
Use it with motion vector shaders  (such as DRME, ReShade Motion vectors, DH_UBER_MOTION, etc...) and reduce the motion vector error tolerance, further removal of ghosting is only possible by decreasing the history length or waiting for updates.

**Comment by Milincho** [comment]
> Use it with motion vector shaders (such as DRME, ReShade Motion vectors, DH_UBER_MOTION, etc...) and reduce the motion vector error tolerance, further removal of ghosting is only possible by decreasing the history length or waiting for updates.

Ahh...   that was it. I wasn't using any motion vectors shader.
Your shader is amazing, man. Any idea when you will release a new version?

**Comment by mj-ehsan** [comment]
Soon... A new GI-AO-Reflection shader will lighten the dark.
