### ISSUE TITLE
ReShade 5.9.2 Support

### ISSUE THREAD

**Issue by nomad5oul** [mj-ehsan/NiceGuy-Shaders#14]
Hi 
Are these shaders still being supported for the new Reshade 5.0+ ?

**Comment by mj-ehsan** [comment]
All 5.0+ versions of ReShade are expected to be supported. except there are reports about NGLighting not compiling in 5.9.x, which I will investigate soon and fix.

**Comment by mj-ehsan** [comment]
ReShade 5.9.2 patch released.
