### ISSUE TITLE
failed to compile error x3000 styntax error: unexpected 'texture2D' expected ','

### ISSUE THREAD

**Issue by SereVene** [mj-ehsan/NiceGuy-Shaders#15]
Hello there, I'm encountering this error on the NGLighting.fx line in my Reshade
I'm using Black dragon viewer (Second life)
[Video](https://streamable.com/1tbx5o)

How can I solve this?
Thanks!
Sere Vene

**Comment by mj-ehsan** [comment]
The latest patch, try it and tell me if it fixed your problem.

**Comment by SereVene** [comment]
It does work! Thank you very much!
