### ISSUE TITLE
Question: Would it be possible to add directional/spot lights into niceguy lamps?

### ISSUE THREAD

**Issue by MOW531** [mj-ehsan/NiceGuy-Shaders#9]
I think spot lights or directional light with a depth limit would work well to give first person view models self shadowing even if it's static.

And would it be possible to have an option to add only shadows to a scene instead of light?

Sorry if this is the wrong place to ask or if it's outside the scope of the shader.

**Comment by mj-ehsan** [comment]
I'd suggest you to open such discussions in the reshade discord. I'm Ehsan2077 there.
